# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-14 19:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('picky_menu_picker', '0004_restaurantlocation_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlocation',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 14, 19, 46, 25, 733626, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
