# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-15 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picky_menu_picker', '0006_auto_20171014_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlocation',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
